accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'

urlpatterns=[
    path('signup/',views.signup_view,name="signup"),
    path('login/',views.login_view,name="login"),
    path('logout/',views.logout_view,name="logout"),
]

akh/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from articles import views as article_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello',include("hello.urls")),
    path('',article_views.index,name="home"),
    path('about',views.about),
    path('articles/',include("articles.urls")),
    path('accounts/',include('accounts.urls'))
]
urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

articles/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
app_name="articles"
urlpatterns=[
    path('',views.index,name="list"),
    path('create/',views.article_create,name="create"),
    url(r'^(?P<slug>[\w-]+)/$',views.article_details,name="detail"),
]

hello/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index,name='index')
    
]

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Article(models.Model):
    title=models.CharField(max_length=100)
    slug=models.SlugField()
    body=models.TextField()
    date=models.DateTimeField(auto_now_add=True)
    thumb=models.ImageField(default="pic1.jpg",blank=True)
    author=models.ForeignKey(User,default=None,on_delete=models.CASCADE)
#python manage.py makemigrations
#python manage.py migrate

    def __str__(self):
        return self.title 

    def snippet(self):
        return self.body[:50]+"............."

hello/models.py
from django.db import models

# Create your models here.

articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model=models.Article
        fields=['title','body','slug','thumb']
        

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout

# Create your views here.
def signup_view(request):
    if request.method=='POST':
        form=UserCreationForm(request.POST)
        if form.is_valid():
            user=form.save()
            login(request,user)
            return redirect('articles:list')
    else:
        form=UserCreationForm()
    return render(request,'accounts/signup.html',{'forms':form})

def login_view(request):
    if request.method=='POST':
        form=AuthenticationForm(data=request.POST)
        if form.is_valid():
            user=form.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get("next"))
            else:
                return redirect('articles:list')
    else:
        form=AuthenticationForm()
    return render(request,'accounts/login.html',{'forms':form})


def logout_view(request):
    if request.method=='POST':
        logout(request)
        return redirect('articles:list')

akh/views.py
from django.shortcuts import render

def index(request):
    return render(request,'home.html')

def about(request):
    return render(request,'about.html')

articles/views.py
from django.shortcuts import render,redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def index(request):
    articles=Article.objects.all().order_by('date')
    return render(request,'articles/article_home.html',{'articles_sent':articles})

def article_details(request,slug):
    article=Article.objects.get(slug=slug)
    return render(request,'articles/article_detail.html',{'article_detail':article})
    #return HttpResponse(slug)

@login_required(login_url="/accounts/login")
def article_create(request):
    if request.method=='POST':
        form=forms.CreateArticle(request.POST,request.FILES)
        if form.is_valid():
            instance=form.save(commit=False)
            instance.author=request.user
            instance.save()
            return redirect('articles:list')
    else:
        form=forms.CreateArticle()
    return render(request,'articles/article_create.html',{'forms':form})

hello/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def index(request):
    return render(request,'hello/home.html')

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}
{% block content %}
<h1>Login</h1>
<form class="site-form" action="{% url 'accounts:login' %}" method="POST">
    {% csrf_token %}
    {{forms}}
    {% if request.GET.next %}
    <input type="hidden" name="next" value="{{request.GET.next}}">
    {% endif %}
    <input type="submit" value="login">
</form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}
{% block content %}
<h1>Signup</h1>
<form class="site-form" action="/accounts/signup/" method="POST">
    {% csrf_token %}
{{forms}}
<input type="submit" value="signup">
</form>
{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}
{% block content %}
<div class="article-create">
    <h2>Create an awesome article</h2>
    <form action="{% url 'articles:create' %}" class="site-form" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{forms}}
    <input type="submit" value="create">
    </form>

</div>
{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}
{% block content %}
<div class="article-detail">
    <div class="article">
        <h1>{{article_detail.title}}</h1>
        <p>{{article_detail.body}}</p>
        <p>{{article_detail.date}}</p>
        <img src="{{article_detail.thumb.url}}" />
        
    </div>

</div>
{% endblock %}

articles/templates/articles/article_home.html
{% extends 'base_layout.html' %}
{% block content %}
    <h1>Articles List</h1>
    <div class="articles">
        {% for article in articles_sent %}
        <div class="article">
            <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a></h2>
            <p>{{article.snippet}}</p>
            <p>{{article.date}}</p>
            <p class="author">added by {{article.author}}</p>
        </div>
        {% endfor %}
    </div>
{% endblock %}

hello/templates/hello/home.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <h1>
        Helllo welcome
    </h1>
    <br>
    <h1>Everyone(Inside hello)</h1>
</body>
</html>

templates/about.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About</title>
</head>
<body>
    <h1>About</h1>
    <br>
    <h1>The articles</h1>
</body>
</html>

templates/base_layout.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Articles</title>

</head>

<body>
    <header class="wrapper">
      <a href="{% url 'articles:list' %}"> <img src="{% static 'l2.PNG' %}" ></a> 
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li>
                    <form class="logout-link" action="{% url 'accounts:logout' %}" method="POST">
                        {% csrf_token %}
                        <input type="submit" value="Logout"></form></li>
                        <li>
                        <a href="{% url 'articles:create' %}">Create</a>
                    
                </li>
                {% else %}
                <li>
                    <a href="{% url 'accounts:login' %}">Login</a></li>
                <li>
                    <a href="{% url 'accounts:signup' %}">Signup</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <div class="wrapper">
        {% block content %}
        {% endblock %}
    </div>

</body>

</html>

templates/home.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello</title>
</head>
<body>
    <h1>
        Helllo welcome
    </h1>
    <br>
    <h1>Everyone</h1>
</body>
</html>